# Generated by Django 5.0.2 on 2024-05-12 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurarPlantaUsuario',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('frecuenciaRiego', models.PositiveIntegerField(default=0)),
                ('fecha_riego', models.DateTimeField(blank=True, null=True)),
                ('frecuenciaPulverizacion', models.PositiveIntegerField(default=0)),
                ('fecha_pulverizacion', models.DateTimeField(blank=True, null=True)),
                ('frecuenciaFertilizacion', models.PositiveIntegerField(default=0)),
                ('fecha_fertilizacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(max_length=255)),
                ('nombre_comun', models.CharField(max_length=255)),
                ('luz', models.CharField(blank=True, max_length=255, null=True)),
                ('ph_minimo', models.FloatField(null=True)),
                ('ph_maximo', models.FloatField(null=True)),
                ('url_foto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_planta_usuario', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('planta_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantasapi.configurarplantausuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='configurarplantausuario',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plantasapi.plantinfo'),
        ),
    ]
