# Generated by Django 5.0.2 on 2024-05-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantasapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='frecuenciaRiego',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
