# Generated by Django 5.0.2 on 2024-05-02 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantasapi', '0002_historial_frecuenciariego'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='fecha_riego',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
