# Generated by Django 5.0.2 on 2024-05-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantasapi', '0003_alter_plantinfo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='fecha_alta',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='configurarplantausuario',
            name='fecha_fertilizacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='configurarplantausuario',
            name='fecha_pulverizacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='configurarplantausuario',
            name='fecha_riego',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='configurarplantausuario',
            name='frecuenciaFertilizacion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configurarplantausuario',
            name='frecuenciaPulverizacion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configurarplantausuario',
            name='frecuenciaRiego',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
