# Generated by Django 5.0.2 on 2024-05-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantasapi', '0004_rename_fecha_alta_historial_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfo',
            name='common_name',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
    ]
