# Generated by Django 5.0.2 on 2024-05-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantasapi', '0004_alter_historial_fecha_riego'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='fecha_fertilizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='fecha_pulverizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='frecuenciaFertilizacion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historial',
            name='frecuenciaPulverizacion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
