# Generated by Django 5.0.2 on 2024-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantasapi', '0007_alter_plantinfo_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfo',
            name='common_name',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
    ]
